version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8005:8000"
    volumes:
      - "./backend:/app"
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: build
    ports:
      - "3005:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    command: npm start
    environment:
      - REACT_APP_API_URL=http://localhost:8005/api
    restart: unless-stopped
